### ISSUE TITLE
breadboard doesn't automatically resole index.js

### ISSUE THREAD

**Issue by peter-mouland** [notonthehighstreet/breadboard#27]
in require / import you would not have to specify `index.js` explicitly.

in breadboard `'/lib/bundler': bundle` isn't recognised, while `'/lib/bundler/index': bundle` is.

**Comment by kosmotaur** [comment]
This was a design decision to avoid ambiguity and have as little logic as possible included in module keys. 

Let me know if this is a significant hindrance or a nice to have 😅
